howtocreate:
  - '&e##===================={ &2Mob&4Arena &e}====================##'
  - '&c/madmin (create|utworz) <nazwa> &6- tworzy arene o podanej nazwie'
  - '&c/madmin (delete|usun) <nazwa> &6- usuwa arene'
  - '&c/madmin (list|lista) &6- lista aren z podzialem na status'
  - '&c/madmin (setpoint1|ustawpunkt1) <nazwa> &6- ustawia 1 rog areny'
  - '&c/madmin (setpoint2|ustawpunkt2) <nazwa> &6- ustawia 2 (przeciwlegly) rog areny'
  - '&c/madmin (setspawn|ustawspawn) <nazwa> &6- ustawia miejsce teleportacji graczy'
  - '&c/madmin (addmobspawn|dodajspawnmobow) <nazwa> <id> &6- dodaje spawn mobow o podanym id'
  - '&c/madmin (deletemobspawn|usunspawnmobow) <nazwa> <id> &6- usuwa spawn o podanym id'
  - '&c/madmin (setlobby|ustawlobby)(1|2) <nazwa> &6- ustawa lobby 1 lub 2'
  - '&c/madmin (kitroom|pokojkitow) <nazwa> &6- ustawia miejsce wyboru klas'
  - '&c/madmin (mode|tryb) <nazwa> &6- wlacza lub wylacza arene z uzytku'
  - '&c/madmin (stop|zatrzymaj) <nazwa> &6- zatrzymuje rozgrywke na podanej arenie'

settings:
  roundtime: 20 # in seconds
  canjointo: '"working"' # spectators can join to arenas: ("enabled"|"working"|"enabled" or "working")
  canceldigging: true
  cancelplacing: false # required if you want to place some tnt
  maxrounds: 10

mobs:
  - zombie
  - skeleton
  - spider
  - creeper
  - zombie pigman
  

kits:
  Knight:
    items:
      - diamond sword
      - 3 potion:8197
    armor:
      - 306
      - 307
      - 308
      - 309
  Tank:
    items:
      - iron sword
      - 2 potion:8229
    armor:
      - 310
      - 311
      - 312
      - 313
  Archer:
    items:
      - wooden sword
      - bow
      - 256 arrow
      - 3 potion:8197
      - bone
    armor:
      - 298
      - 299
      - 300
      - 301
  Chemist:
    items:
      - stone sword
      - 9 potion:16428
      - 9 potion:16388
      - 9 potion:16389
      - 3 potion:8197
      - potion:8226
    armor:
      - 314
      - 315
      - 316
      - 317
  Oddjob:
    items:
      - stone sword
      - flint and steel
      - 2 netherrack
      - 4 tnt
      - 3 potion:8197
    armor:
      - 298
      - 299
      - 300
      - 301

reward:
  round:
    1:
      - 'stone sword of Sharpness 5 named ""kupa""'
      - '3 stone'
      - '5 cobweb'
